### ISSUE TITLE
Getting 500 Internal Server error for VAT old and new API endpoints

### ISSUE THREAD

**Issue by audupa** [hmrc/vat-api#130] opened 2018-04-24 10:44 UTC
Hi there,

We are getting 500 Internal Server error when we try to hit obligation API using the below API's

**New one**
`https://test-api.service.hmrc.gov.uk/organisations/vat/666329393/obligations?from=2017-01-25&to=2017-02-25&status=O` and 

**Old one**
`https://test-api.service.hmrc.gov.uk/vat/666329393/obligations?from=2017-01-25&to=2017-02-25&status=O`.
This is blocking us from testing. Could someone please help us resolve this issue?

Thanks,
Akshatha

**Comment by MarkAKelly** [comment] 2018-04-24 10:46
Hi @audupa,

This is a known issue to the platform and should be resolved shortly.  Please try again shortly.

Thanks,

Mark

**Comment by audupa** [comment] 2018-04-24 10:48
Thanks Mark. Could you please let us know once the issue is resolved. We are seeing this issue since yesterday.

**Comment by CoppensBart** [comment] 2018-04-24 11:28
Same issue for me

**Comment by aswinpillai** [comment] 2018-04-25 08:09
Facing the same issue while posting a VAT return. Could you please update us once the issue is resolved.

**Comment by mathiasbanda** [comment] 2018-04-26 10:49
Still no update?

**Comment by MarkAKelly** [comment] 2018-04-26 13:33
As this is related to [#135](https://github.com/hmrc/vat-api/issues/135, I'm going to close this issue thread.  Feel free to reopen @aswinpillai if you feel you need to.

Cheers, 
Mark

**Closed by MarkAKelly** 2018-04-26 13:33 UTC
Labels: platform issue

**Comment by audupa** [comment] 2018-04-30 12:37
Hi @MarkAKelly  I am again seeing internal server error after creating the test user using the create test user API with the "mtd-vat" in the payload request.

**Comment by scottylace** [comment] 2018-05-01 08:50
Hi @audupa,

If you're using the same URL and parameters as your original post a week ago: 

`https://test-api.service.hmrc.gov.uk/organisations/vat/666329393/obligations?from=2017-01-25&to=2017-02-25&status=O`

then you will see a 500, this is a known issue that was highlighted under on issue #62. As per the comment on #62 a fix has been identified for this and is to be prioritised with future work. 

To work around the 500 issue for now you can supply a 'Gov-Test-Scenario' header value or extend the `from` and `to` date range to be greater than 6 months.

**Comment by audupa** [comment] 2018-05-01 10:57
@scottylace Hi. I just tried the workaround by increasing the date range for more than 6 months and it worked. Thanks
