### ISSUE TITLE
API Server Down?

### ISSUE THREAD

**Issue by RichardTaxaddict** [hmrc/vat-api#706] opened 2020-01-07 10:58 UTC
Hello - getting a few users this morning trying to file and reporting 

Error requesting data on server. Server Error, The organisation/vat API is currently unavailable.

![image](https://user-images.githubusercontent.com/50072190/71890570-7c370200-313c-11ea-8e88-4d7ab5e75381.png)

**Comment by StuBramley** [comment] 2020-01-07 11:06
We've also got users experiencing the same error...

**Comment by TS-grantlebrun** [comment] 2020-01-07 11:09
There is a "Live Incident" reported here: https://api-platform-status.production.tax.service.gov.uk/incidents/0yf5rg74ch9l

However we've seen all requests failing since 10am - not 10.46 as reported there.

**Comment by RichardTaxaddict** [comment] 2020-01-07 11:12
It would be helpful if HMRC reported it on the server update. Providers and VAT payers go into meltdown (especially on filing deadline day) when this happens as we have to figure out who's end is failing.

https://www.gov.uk/government/publications/making-tax-digital-for-vat-service-availability-and-issues/making-tax-digital-for-vat-service-availability-and-issues

**Comment by mtd-api-team** [comment] 2020-01-07 11:48
We can confirm that the VAT API is currently unavailable.  You should all have had communication directly about this issue that HMRC are facing.

As the customer facing API team, we can only apologise for this inconvenience.  VAT is not the only area affected, and HMRC are working to resolve this as soon as possible.

We take your point about the service availability page - the team responsible for that have been informed and should be updating it more promptly.

**Comment by StuBramley** [comment] 2020-01-07 12:18
Hi,

Unfortunately no email or other direct contact from HMRC to inform us of the issue proactively. We have received a reply to our email which has confirmed the problem and shared this same link (which is very useful as we weren't previously aware of it). 

We have subscribed to updates so hopefully will be informed as soon as things are back up and running and can then inform our users accordingly.

**Comment by mtd-api-team** [comment] 2020-01-07 13:48
The issue appears to have been resolved, and we have made our API available for use again.

Apologies again for the interruption of service.

**Comment by mtd-api-team** [comment] 2020-01-08 12:40
Hi all

Unfortunately HMRC is experiencing an issue again, and VAT API is currently unavailable.

Again we apologise for this inconvenience. VAT is not the only area affected, and HMRC are working to resolve this as soon as possible.

Regards

**Comment by mtd-api-team** [comment] 2020-01-08 13:21
The issue appears to have been resolved, and we have made our API available for use again.

Apologies again for the interruption of service.

**Comment by RichardTaxaddict** [comment] 2020-01-08 18:07
Thanks.

Was it capacity/overload issue due to filing deadline? Just so we know and can encourage users to file earlier than deadline day. Someone told me it wasn't just MTD filings today, but registering new taxpayers, too?
Thanks

**Comment by mtd-api-team** [comment] 2020-01-09 10:08
Hi all

Unfortunately HMRC is experiencing an issue again this morning, and VAT API is currently unavailable.

Again we apologise for this inconvenience. HMRC are working to resolve this as soon as possible.

Regards

**Comment by RichardTaxaddict** [comment] 2020-01-09 10:17
Hi - thanks for the heads up. Any indication of the cause? Just so we can keep clients informed.

**Comment by mtd-api-team** [comment] 2020-01-09 10:32
Hi @RichardTaxaddict,

HMRC are still investigating the cause of this - unfortunately we are probably not in the best place to communicate the results as and when they arrive.  

Again, SDST are the best placed to respond to queries of this nature, but as we can get a message out to everyone quickly through this channel we thought we would do so.

**Comment by mtd-api-team** [comment] 2020-01-09 13:42
The issue appears to have been resolved, and we have made our API available for use again.

Apologies again for the interruption of service.

**Comment by mtd-api-team** [comment] 2020-01-23 14:09
Hi all

Unfortunately HMRC is experiencing an issue again this afternoon, and VAT API is currently unavailable.

We apologise for this inconvenience. HMRC are working to resolve this as soon as possible.

Regards

**Comment by mtd-api-team** [comment] 2020-01-23 15:15
The issue appears to have been resolved, and we have made our API available for use again.

Apologies again for the interruption of service.

**Comment by mtd-api-team** [comment] 2020-02-04 11:57
Hi all

I'm closing this Issue as the downstream issues which caused these problems have been resolved for a few days now. Apologies again for any inconvenience this caused.

Regards

**Closed by mtd-api-team** 2020-02-04 11:57 UTC
