### ISSUE TITLE
Submit return, get HTTP 201 (Created), however obligation remains Open

### ISSUE THREAD

**Issue by JeeBeePee** [hmrc/vat-api#560] opened 2019-04-07 21:35 UTC
I know this isn't for production issues, but I wanted to see if any other developers have seen this behaviour since April 1st.  We've never seen it with pilot users, nor in the sandbox, however we now have three cases where the prod environment has behaved as follows but the user is signed up for MTD as we are not seeing "user not authorised to access this VRN" errors - we can retrieve data from the endpoints for the VRN (although the data returned is, IMHO, incorrect)

- Retrieve open obligations.  An open return with period key e.g. 0219 is returned.
- Retrieve fulfilled obligations.  Some fulfilled obligations are returned, even though they can't have been submitted under the MTD regime.
- Submit a return for our open period key 0219.
- Receive HTTP 201 (created) for the submitted return, but the response does not contain any reference numbers.
- The user gets a DD email from HMRC.
- Retrieve open obligations.  The return with period key 0219 is still open, even after several days!
- Retrieve the VAT return for 0219.  The endpoint returns the data we submitted previously, even though the obligations endpoint thinks the return is still open!
- The user contacts the HMRC MTD online services team and is told that the return hasn't been submitted (even though they have an email from HMRC telling them that a DD payment has been scheduled)

Now, we turn to the support model, which is in development.  The SDS team won't investigate individual cases because they don't have access to the data, the MTD helpdesk won't discuss the issue with the software vendor because they'll only talk to the business, and neither the business nor the MTD Helpdesk has enough technical knowledge to discuss the issue in sufficient detail.

Our code hasn't changed and we've been happily submitting returns for most users, and we cannot replicate in the sandbox (not that we expected to be able to, given that it's all canned data).

My hunch is that there's a migration issue, but I can't work out how to drive and co-ordinate the support effort.

**Comment by tim-jackson** [comment] 2019-04-08 08:42
@JeeBeePee We are also seeing this issue with some returns - along with the 201, we also get a receipt id. The client is also telling us that HMRC has told them that the return is filed, yet I just don't think the issue lies with us. Very frustrating.

**Comment by JeeBeePee** [comment] 2019-04-08 09:44
Great, so it's not just me. Could someone from HMRC suggest how we can troubleshoot this issue? Conference call with SDS, the MTD helpdesk, and us?

The HMRC support model makes it impossible for software vendors to provide what I would consider to be a good standard of support in this case.

**Comment by pwatts001** [comment] 2019-04-08 09:52
@JeeBeePee @tim-jackson I've seen this issue for numerous VRNs.

The problem seems to be that the Get Obligations API can return what appears to be dummy/fake data. You can see this by:

1) Obligations going back to before the implementation of MTD (early 2018)
2) Numerous obligations marked as fulfilled where the returns are consistently filled on 1st of the last month of the period i.e. early returns (e.g period 1st Jan - 30th Mar where return was filed 1st Mar)
3) Obligations remaining open after returns are filed (despite receiving an HMRC ID for the original submission)

I have attached a screenshot to demonstrate this.
![mtd](https://user-images.githubusercontent.com/12070540/55714952-8da38000-59eb-11e9-9491-f5628efb0c07.png)

It's extremely frustrating because there seems to be no HMRC support on this and we're getting customers complaining and phoning us up on a daily basis.

**Comment by GrahamHDawson** [comment] 2019-04-08 10:00
This is **very** worrying - not just the bugs (inevitable I suppose) but the lack of a fast track support route to sort things out.
We were led to believe that contacting the SDS Team with a CorrelationID would be enough to have any problem investigated.

**Comment by MarkAKelly** [comment] 2019-04-08 10:57
@JeeBeePee @pwatts001 @tim-jackson @GrahamHDawson 

We are taking a look into this particular scenario and getting in touch with the appropriate HMRC teams to get a view on what's happening in this instance.  Although we know its not the preferred route for you guys, we will need VRNs/timestamps/correlationId's sent to SDST for us to properly identify your requests and track them.  If you mention that the VAT API team have referred you then it should speed up the process.

We will respond in this thread if we find anything that is relevant.

Cheers,

Mark

**Comment by JeeBeePee** [comment] 2019-04-08 11:14
Hi Mark

I am happy to provide VRNs (and indeed did send details to the SDS email address) but was directed to get the user to call the MTD helpdesk.

In this instance, I'm sorry but I don't think that posting on this thread if you find something is good enough. Could you provide another update whether you've found anything or not before close of business today? And also update your own status page to say you are investigating an issue with data inconsistency? Because, frankly, this is making us look like fools to our non-technical customers.

Thanks

**Comment by pwatts001** [comment] 2019-04-08 11:48
@MarkAKelly, when we contact SDS about these we're told the customer should directly contact HMRC too. Then we've experienced HMRC telling the customer it's the software vendors fault!

We've seen the same problem with +c10 VRNs. If HMRC are unable to resolve the root cause of the issue then there needs to be a proper channel to communicate occurrences so they can be individually resolved.

Completely agree with @JeeBeePee, we look incompetent to our customers.

**Comment by GrahamHDawson** [comment] 2019-04-08 12:29
@pwatts001 , I take it that the common warning factor here is that Obligations shows items that don't belong to the end-user.

**Comment by JeeBeePee** [comment] 2019-04-08 15:56
@MarkAKelly Is there going to be an update on this please?

To reiterate - your production environment returns inaccurate data for multiple users. So far we've been promised some teams that would usually need timestamps, but don't have them, are going to have a look and that the support process will be reviewed.

Is there a phone number for SDS Team? I've trawled my emails but can't find one.

**Comment by MarkAKelly** [comment] 2019-04-09 10:10
@JeeBeePee we have raised this issue as a matter of urgency - the program are finding a way to best support these issues and in the future, there should be a better way of raising live support issues with the MTD programme.  

I really do understand your frustration but for the time being, we as a development team have been advised to suggest that through this channel, we are unable to progress live service cases. As this enquiry relates to a VAT issue with their account, we recommend that the user contact HMRC directly, via the contact link:
https://www.gov.uk/government/organisations/hm-revenue-customs/contact/vat-enquiries

I will stress that we have raised this with the programme as a priority and it is being looked into.

Thanks,

Mark

**Comment by JeeBeePee** [comment] 2019-04-09 10:38
@MarkAKelly That's good to hear. Any chance of an update to the service status page so that we have something to point customers to rather than asking them to take our word for it? I don't really fancy sending them links to github.

**Comment by GrahamHDawson** [comment] 2019-04-09 10:42
@MarkAKelly 
Maybe the FAQs need a 'Live Service Issues' topic with the link you provided above.
Then it could be updated if with any future method of progressing live issues

**Comment by MarkAKelly** [comment] 2019-04-09 10:45
@JeeBeePee, @tim-jackson,  @pwatts001, @GrahamHDawson,

Just as an addition to the previous, we can help fast track your support if you supply the following information to the following email address: georgina.jones@digital.hmrc.gov.uk.  

@JeeBeePee good point, I'll look at getting something done with that.  For your own purposes, if you want direct updates on this case then we will contact you through the above email address if you supply a specific return address.

@GrahamHDawson I'll put something and update it when the program have decided how best to proceed.

Mark

**Comment by mtd-api-team** [comment] 2019-04-10 22:40
I'm closing this issue.  If all in the thread need further correspondence use georgina.jones@hmrc.gov.uk.

Mark

**Closed** 2019-04-10 22:40 UTC
