### ISSUE TITLE
Refresh tokens expiring early 

### ISSUE THREAD

**Issue by JeeBeePee** [hmrc/vat-api#658] opened 2019-07-08 09:19 UTC
Anyone else seeing refresh tokens expiring after 3 months instead of the promised 18?

**Comment by mathiasbanda** [comment] 2019-07-08 09:54
Yes we asked HMRC that same question and here is a quote from the response:
"We are aware that a number of separate applications received this error between 14:00 and 18:00 on the 3rd July". It goes on to say, "We do believe this issue to have been short lived and now resolved."

Ultimately those token would be invalid meaning the application would need to get new ones aka require reauthorizing.

Hope this helps

**Comment by JeeBeePee** [comment] 2019-07-08 10:11
Thanks. Turns out it isn't short lived as we've had it happen this morning. Was it the SDS Team who said that?

**Comment by mathiasbanda** [comment] 2019-07-08 10:23
No this came from the production team. The SDS team seem to abdicate all live issues - which I find annoying because it should be much easier and quicker for them to get answers - but equally i appreciate the necessity of building the walls

**Comment by GrahamHDawson** [comment] 2019-07-08 15:23
> No this came from the production team.

Not sure I get who **that** is?

**Comment by JeeBeePee** [comment] 2019-07-09 09:52
Also wondering what the contact details are for the "production team"

**Comment by mtd-api-team** [comment] 2019-07-09 10:10
Hi all

We are not sure who is meant by Production team

We are unable to assist with Auth issues because they are outside our control. Please get in touch with SDST by emailing SDSTeam@hmrc.gov.uk, and they will be able to contact the relevant team.

Regards

**Comment by mathiasbanda** [comment] 2019-07-09 10:17
Please ignore "production team". We asked our account manager. And that's what we got back.

**Comment by GrahamHDawson** [comment] 2019-07-16 11:19
Did anyone get an answer from SDSTeam - this has happened to use today.
We got the refresh token about a month ago but had to reauthorise to post a VAT Return as the token didn't work.

**Comment by mathiasbanda** [comment] 2019-07-16 11:37
We are just advising our customers to re-authorise when they get that.

**Comment by stuy1974** [comment] 2019-07-16 11:42
This is a solution but poor form from HMRC! Is there a fix in the pipeline?

**Comment by nigelrainer** [comment] 2019-07-16 12:39
We are seeing increasing numbers of these with refresh tokens expiring in just a few weeks.  Raising it with SDST just gets the same stock answer of "this is only happening in a few cases" and "get the client to re-authorise".  There is something deeper here that they are not admitting to.

**Comment by mtd-api-team** [comment] 2019-07-18 13:50
In order for these instances to be further investigated please ensure that you provide SDST with as much information as possible (e.g. exact times and source IPs) so that the relevant teams might then be able to isolate these events.

**Comment by mtd-api-team** [comment] 2019-07-18 13:52
Your attention is also drawn to section 5 (Refreshing an access token) of [Authorisation - User-restricted endpoints](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) which warns of the possibility of inadvertently invalidating your own refresh tokens by making concurrent refresh requests.

**Comment by GrahamHDawson** [comment] 2019-07-18 16:34
Hi mtd-api-team,

Can I ask how we contact  SDSTeam@hmrc.gov.uk in such a way that the issue is dealt with quickly.
Do they have a specific person or department dealing with 'live' issues, or is there some other method (possibly using the email subject line) that would ensure the email gets to the right place?

I know they were/are consulting on how to make communications between developers and end users and the SDSTeam more efficient - did anything come of that?

In our case the problem arose with our own accounts system and I was present when we used the software to grant authority and received Access and Refresh tokens on 29/05/2019 and when we tried to use the RefreshToken to get a renewed AccessToken on 16/07/2019 (roughly 7 weeks later)

We got an Error 400 at that point with the payload...
{"error":"invalid_grant","error_description":"refresh_token is invalid"}

Because this is our own accounts system only one user has access - so the concurrent refresh requests point above is not relevant here.

After re-authorisation we successfully retrieved Obligations and submitted a VAT Return for an outstanding period, but we shouldn't have needed to re-authorise.

**Comment by JeeBeePee** [comment] 2019-07-18 22:40
**Can I ask how we contact SDSTeam@hmrc.gov.uk in such a way that the issue is dealt with quickly.**

LOL. If you can find that out, you'll be the most popular person on this board.

Refresh tokens are supposed to be valid for 18 months. Turns out that a lot of them are not. Why would SDST need tons of info from vendors to troubleshoot? HMRC are making the decision to expire tokens - simply scrape your logs for refresh tokens expired on first use; the system hasn't yet been live for 18 months, so those are the problem tokens.

It seems that absolutely none of the lessons taken from the first webinar have been acted upon. None whatsoever. We have clients asking us if we're going to add x tax to our system, or y tax when it's "made digital". We're replying that we can't commit, because the business case falls away when considering the enormous support costs caused by the ineptness of HMRC.

**Comment by mathiasbanda** [comment] 2019-07-18 23:02
This isn't an explaination for what's happening with tokens just an addition for information. I noticed when I enforced TLS 1.2 the previous refresh tokens (obtained under TLS 1.1) all failed 100%

**Comment by nigelrainer** [comment] 2019-07-19 07:13
@GrahamHDawson - you could try escalating to Louise Tarpy (louise.tarpy@hmrc.gov.uk)

**Comment by nigelrainer** [comment] 2019-07-19 07:16
@mtd-api-team - our logs, code reviews and discussion with SDST to date indicate that we are communicating with OAuth correctly and evidence is that this is an issue at the HMRC end.

**Comment by TomLoderLM** [comment] 2019-07-25 11:29
We have a desktop application that we seem to be having a high volume of users where the refresh token is not being accepted on their second or third VAT return.

**Comment by GrahamHDawson** [comment] 2019-07-25 11:55
Hi Tom,
Also using a desktop application here.
In our case the refresh token was re-issued on 03/06/19 and failed on 16/07/19 - that's just 43 days later.

**Comment by nigelrainer** [comment] 2019-07-25 11:58
@TomLoderLM, @GrahamHDawson - I don't think it's limited to application type.  Ours is a SaaS web app and we are still getting this issue.

**Comment by AlexJSH** [comment] 2020-11-05 12:08
We are currently seeing a number of clients whose Access Token's will not refresh but have their Refresh Token has allegedly not expired yet - eg one I'm looking at right now the Refresh Token is due to expire at 2PM this afternoon but the Access Token refresh attempt return 'refresh_token is invalid' error.
This means our software is not currently able to point them to the 'Grant Authority' web page and we just end up with a nasty invalid token error and a support call....

This will be the first flush of clients whose Refresh Tokens are now reaching the full 18 month point from starting MTD.

Is anyone else seeing discrepancies between the alleged expiry date and actual at the 18 month point? I don't have a feel yet for if the date is a day our or a week out or a month out.

Thanks

**Comment by AlexJSH** [comment] 2020-11-05 12:10
To clarify - we are seeing enough cases that it is unlikely that these Access Tokens are being invalidated by being refreshed via a different route.

**Comment by mathiasbanda** [comment] 2020-11-05 12:41
We are getting loads of those and advising our users to go through the authorization process from the start.

**Comment by nigelrainer** [comment] 2020-11-05 13:54
We have had a number of these in the last week and they have been happening after receiving a strange error on return submission.  The error comes back as HTML rather than JSON and just says “Oops, an error occurred”.  At this point the token appears to be invalidated - we have informed SDST who are apparently investigating.

**Comment by AlexJSH** [comment] 2020-11-05 15:24
Thanks for quick responses
@mathiasbanda - yes that's the route we are taking everyone too - its a pain though as the software is set to auto lead them there once past expiry date of refresh token however this unexpected expiry is generating a support call each time.
@nigelrainer - our's are definitely not due to any error occurring on return submission - good luck with that one.

**Comment by mathiasbanda** [comment] 2020-11-05 19:05
@nigelrainer html that's a first i have heard of from day 1 of mtd. Should be json, please us all posted if u get to the root cause, cheers

**Comment by JeeBeePee** [comment] 2020-11-06 14:07
We also saw the /returns endpoint spitting out an HTML page for a HTTP 500 error, but that seemed to go away after an hour or so. SDST didn't even pick it up and don't seem to have investigated it properly, merely telling me that it resolved itself.

Today, we're seeing HTTP 401s come back from /returns, despite passing the same access token that we've just successfully hit the other endpoints with.  The only resolution that seems to work at the moment is to clear your stored access and refresh tokens AND get the user to de-authorise your application.  Then go through the authorisation workflow.

There doesn't seem to be a correlation between this issue and the 18 month authorisation expiry for us.

I've emailed SDST team, but they do like to take their time coming back, and of course https://api-platform-status.production.tax.service.gov.uk shows the service is operating normally.

**Comment by nigelrainer** [comment] 2020-11-06 15:29
@mathiasbanda I've just received the following from SDST:

"We have received the confirmation that there was an issue with one of the back-end systems, I can confirm a fix has now been implemented which will prevent the HTML error recurring."

**Comment by AlexJSH** [comment] 2020-11-23 17:11
I've been tracking some due to expire refresh tokens over the last week and have full proof that they are expiring early. The two I followed had been disabled on the clients system so there was no way they inadvertently invalidated the tokens. I found the following:

Refresh Token Due to expire 24/11/2020 16:12:27 
- Worked on 20/11/2020 @ 09:58
- Failed on 23/11/2020 @ 17:00 with "refresh_token is invalid" message

Refresh Token Due to expire 24/11/2020 16:08:15 
- Worked on 20/11/2020 @ 09:59
- Failed on 23/11/2020 @ 17:02 with "refresh_token is invalid" message

Unfortunately i was unable to track them over the weekend so can't precisely say they expired one day early or two days etc...

@mtd-api-team your comments would be greatly appreciated

**Comment by hmrc-api-team** [comment] 2020-11-23 17:23
Hi @AlexJSH,

How are you determining the expected expiry date-time for your tokens? We weren't aware that this information was being exposed to users.

Kind regards,
MTD api team.

**Comment by JeeBeePee** [comment] 2020-11-23 20:02
We've also seen this. SDS Team claims there's no issue.

Another one we have is authorisations that are older than 18 months still returning access tokens, but the access tokens don't work - we get a 403 back. Users have to revoke our app's authority with HMRC manually, then re-authorise. Again, SDS Team claiming nothing wrong.

**Comment by AlexJSH** [comment] 2020-11-24 10:56
@mtd-api-team A very interesting question! Our MTD comms DLL was written by a third party and when we run the authorise process it returns the access token with expiry date/time (4 hrs) and the refresh token with expiry date/time (18 months) and i was told that these expiry dates came from HMRC but maybe they are calculated.

We have been storing these expiry dates and using them as triggers for the refresh access token or re-authorise of software processes - maybe under slight false pretenses.

Access to the 3rd party developer is difficult. Can someone @ HMRC, or another developer with deeper technical knowledge, please confirm if expiry date/time is supplied by HMRC with the access token? And can HMRC define precisely the 18 month expiry calculation - then i can check that the DLL is correct/wrong and report back if this is a true issue or a bit of smoke and mirrors.

Many thanks

Alex

**Comment by cb-rfk** [comment] 2020-11-24 11:28
@AlexJSH 
Yes, we were also lead to believe at the start of development that tokens expired after those timeframes and we calculate and save their expiry timestamp accordingly.

We are also seeing a few examples of users' tokens expiring before these calculated dates, and have had to add functionality allowing users to clear their tokens and re-authenticate via the gateway.

**Comment by mathiasbanda** [comment] 2020-11-24 11:28
The 4 hour expiry time on the access token is correct and it comes from HMRC. I believe the 18 months is correct too. I say believe because I have actually never bothered with it, i excluded it from our design decisions. In the early days I found the 4 hours was a bit hit and miss so I we don't rely on it.

**Comment by mathiasbanda** [comment] 2020-11-24 11:56
I wasn't been a while so I went and looked. Access tokens definitely come with an 'expires_in' value when they're issued. So I guess could easily be calculated but equally can be stored as issued

**Comment by nigelrainer** [comment] 2021-01-28 09:46
We have had a number of further occurrences of getting back an HTML error rather than a JSON message with the content "Oops, an error occurred".  This is an example:

<head>
        <title>Error</title>
        <style>
            html, body, pre {
                margin: 0;
                padding: 0;
                font-family: Monaco, 'Lucida Console', monospace;
                background: #ECECEC;
            }
            h1 {
                margin: 0;
                background: #A31012;
                padding: 20px 45px;
                color: #fff;
                text-shadow: 1px 1px 1px rgba(0,0,0,.3);
                border-bottom: 1px solid #690000;
                font-size: 28px;
            }
            p#detail {
                margin: 0;
                padding: 15px 45px;
                background: #F5A0A0;
                border-top: 4px solid #D36D6D;
                color: #730000;
                text-shadow: 1px 1px 1px rgba(255,255,255,.3);
                font-size: 14px;
                border-bottom: 1px solid #BA7A7A;
            }
        </style>
    </head>
    <body>
        <h1>Oops, an error occurred</h1>

        <p id="detail">
            This exception has been logged with id <strong>7ihhi4hab</strong>.
        </p>

    </body>
</html>

This is on a submission and is then immediately followed by an invalid_grant and an expired token.

We have raised this with SDST a number of times and just get back "Apologies for the delay in response.  There was an issue on the morning of the XXth January which meant that the service had to be shuttered for a short period of time.   Thanks for raising this & apologies for the inconvenience."

I have asked them to explain:

-	What at their end is causing this?
-	When the documentation will be updated to reflect that this type of error is possible?
-	When this unhandled API error is to be fixed?

I don't hold out much hope of an answer, though.

**Comment by hmrc-api-team** [comment] 2021-09-02 10:47
Hello, we are closing this issue due to age. If you still have any persisting issues please feel free to open a new issue.

**Closed by hmrc-api-team** 2021-09-02 10:47 UTC
