### ISSUE TITLE
Error 503 submitting vat return

### ISSUE THREAD

**Issue by EdsDevelopers** [hmrc/vat-api#235] opened 2018-09-03 15:52 UTC
We have an application almost fully working with your api's, apart from submitting and recovering returns. We are aware that we can only recover returns posted by our own app, so we can't test this until we have made a successful submission, we are issuing a post request with the following details. This consistently receives a error 503 response, after a timeout delay.

Headers
Accept: application/vnd.hmrc.1.0+json
Content-Type: application/json
Authorization: Bearer '+AccessToken

URL (organization details including vat id created through hello service)
https://test-api.service.hmrc.gov.uk/organisations/vat/666257601/returns

Body (No Fields)
{"periodKey": "18A4","vatDueSales": 93000.00,"vatDueAcquisitions": 0.00,"totalVatDue": 93000.00,"vatReclaimedCurrPeriod": 58000.00,"netVatDue": 35000.00,"vatDueSales": 1500300.00,"totalValueSalesExVAT": 123456.00,"totalValuePurchasesExVAT": 0.00,"totalValueGoodsSuppliedExVAT": 93000.00,"totalAcquisitionsExVAT": 0.00,"finalised": true} 

If you could shed some light on this, it would be appreciated.

Thanks 

John.

**Comment by jonathanleather** [comment] 2018-09-04 07:15
Hey @EdsDevelopers 

From inspecting the body of your request it appears you have a duplicate of `vatDueSales`.
Removing this should work, or at least get you further.

Let me know if you have any further issues.

Cheers
Jon

**Closed** 2018-09-13 07:03 UTC
